### PR TITLE
Add Viewport-Height explainer

### PR DESCRIPTION
**Pull request by domfarolino**
This PR is to help @tarunban out in #6, by porting his document over to an explainer in this repo.

I've made some very small adjustments, but Tarun can you confirm that this accurately captures what your explainer doc has?

### CODE REVIEW

**Comment by yoavweiss** [comment]
@domfarolino - Thanks for converting the explainer! 
From an IPR perspective, I think it'd be better if you and Tarun joined the WICG.

**Comment by domfarolino** [comment]
Sounds good. I was surprised that I was not a member actually. I've just requested.

**Review by tarunban — APPROVED** [review]
This lgtm. Thanks for writing this down.

**Comment by eeeps** [comment]
The usage example and explanation of the lazyloading use case on root documents are solid.

I don't think the spec text belongs in the explainer, as there's also a PR on the actual spec.

Also, if there aren't any additional security and privacy considerations for this particular hint, maybe remove that section, too.

Also also, I wouldn't mind adding some mention of the subresource-centric use cases for this hint. Here's what I came up with in the [Discourse discussion](https://discourse.wicg.io/t/viewport-height-client-hint-proposal/4993/2):

1. Optimizing height-constrained images, in the absence of a `Height` hint (which would depend on heights being added to `sizes` which sounds non-trivial)
2. Completely server-side art direction

Those could live in a separate PR that I'm happy to work up, however.

**Comment by eeeps** [comment]
One question I have about the optimizing-for-the-fold use case: do we need the viewport height/width, or (and?) _inline/block_ dimensions?

I have an instinct telling me that when you're dealing in layout (rather than with subresources, which have a fixed orientation and shouldn't [usually] rotate along with the `writing-mode`), you should think in inline and block dimensions, rather than height and width. This is more resilient to different (and [variable](https://ericportis.com/etc/writing-mode-and-images/)) writing modes.

I suppose my question is: for optimizing-for-the-fold to work, does the server need to know the page's content and layout in addition to both the Viewport Height and Viewport Width? If so, this distinction is moot, as the server knows the writing direction and its easy to know whether the fold is horizontal or vertical. If there are opportunities to make good decisions with more limited information, however, perhaps it makes sense to deal in inline and block dimensions, rather than height and width, for this use case.

**Comment by domfarolino** [comment]
@tarunban Would you be able to address some of the feedback above in the original doc and I can port it over to this PR here? (Also some of the questions above seem probably more answerable by you too :) )

**Comment by tarunban** [comment]
@eeeps Not sure if I understood the question correctly but my understanding is the for optimizing above-the-fold, the server needs to know the page content, layout as well as viewport-height and viewport-width. With the limited information (just the inline/block dimensions), I believe it's difficult for the publisher to predict which images are likely to appear in the viewport in the first HTML request itself?

**Comment by domfarolino** [comment]
I think I've addressed most of the feedback in this PR after updating the text with what Tarun had added in his explainer Google Doc.

> Also also, I wouldn't mind adding some mention of the subresource-centric use cases for this hint. Here's what I came up with in the Discourse discussion:
...
> Those could live in a separate PR that I'm happy to work up, however.

Sure, it sounds like you've got a good idea of what you might want to include so I'm happy to defer to you. Feel free to either add commits to this PR or in another one.

**Comment by eeeps** [comment]
If the server has access to everything, then I think the logical-vs-physical dimensions distinction is moot, and the shortest line to solving the use case you outline here is a Height companion to the Width we already have...

So, looks good, merging.

And I'll file some follow-up issues to:
- flesh out the subresource use case(s?), in addition to the navigation use case outlined here
- think through possible use cases for logical dimensions, in addition to physical ones.

Thanks for this! (And your patience!)

**Pull request merged**
